# Auto-generated by Backstage template 'request-gcp-vm' -- do not hand-edit
# region/machine settings, resubmit the template instead.

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = "${{ values.region }}"
}

variable "project_id" {
  type = string
}

resource "google_compute_instance" "${{ values.serviceName }}" {
  name         = "${{ values.serviceName }}"
  machine_type = "${{ values.machineType }}"
  zone         = "${{ values.region }}-a"

  labels = {
    environment = "${{ values.environment }}"
    requester   = "${{ values.requester }}"
    ttl_hours   = "${{ values.ttlHours }}"
  }

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-12"
    }
  }

  network_interface {
    network = "default"
    access_config {}
  }
}

output "vm_name" {
  value = google_compute_instance.${{ values.serviceName }}.name
}

output "vm_ip" {
  value = google_compute_instance.${{ values.serviceName }}.network_interface[0].access_config[0].nat_ip
}
